name: Nightly Mutation Testing

on:
  release:
    types: [created]
#  schedule:
#    - cron: '*/5 * * * *'

jobs:
  check_date:
    runs-on: ubuntu-latest
    name: Check latest commit
    outputs:
      should_run: ${{ steps.should_run.outputs.should_run }}
    steps:
      - uses: actions/checkout@v2
      - name: print latest_commit
        run: echo ${{ github.sha }}
      - id: should_run
        continue-on-error: true
        name: Check latest commit is less than a day
        run: test -z $(git rev-list --after="24 hours" ${{ github.sha }}) && echo "::set-output name=should_run::false" || echo "::set-output name=should_run::true"
    
  test:
    needs: check_date
    if: ${{ needs.check_date.outputs.should_run == 'true' }}
    runs-on: ubuntu-latest
    name: Mutation Testing
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Execute Mutation Testing with Maven
      run: mvn test-compile org.pitest:pitest-maven:mutationCoverage --batch-mode --file pom.xml
