name: Nightly Mutation Testing

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Execute Mutation Testing with Maven
      run: mvn test-compile org.pitest:pitest-maven:mutationCoverage --batch-mode --file pom.xml
